# This publishes to PyPI. See: https://github.com/pypa/gh-action-pypi-publish
name: Publish cirq-superstaq to PyPI

on:
  push:
    branches: [main]

jobs:
  publish:
    name: Publish cirq-superstaq to PyPI
    runs-on: ubuntu-latest 
    steps:
    - name: Publish new version to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        ./update-version-tag.sh
